
tasks:
    install-aws-cli:
        name: Install aws cli
        command:
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        triggeredBy:
            - postDevcontainerStart