
tasks:
    install-aws-cli:
        name: Install aws cli
        command:
          mkdir -p ./aws-install
          cd aws-install
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          cd ..
        triggeredBy:
            - postDevcontainerStart